export const FULL_POSE_CONNECTIONS: Array<[string, string]> = [
  ["nose", "left_eye"],
  ["left_eye", "left_ear"],
  ["nose", "right_eye"],
  ["right_eye", "right_ear"],
  ["nose", "mouth_left"],
  ["nose", "mouth_right"],
  ["left_shoulder", "right_shoulder"],
  ["left_shoulder", "left_elbow"],
  ["left_elbow", "left_wrist"],
  ["right_shoulder", "right_elbow"],
  ["right_elbow", "right_wrist"],
  ["left_shoulder", "left_hip"],
  ["right_shoulder", "right_hip"],
  ["left_hip", "right_hip"],
  ["left_hip", "left_knee"],
  ["left_knee", "left_ankle"],
  ["left_ankle", "left_heel"],
  ["left_heel", "left_foot_index"],
  ["right_hip", "right_knee"],
  ["right_knee", "right_ankle"],
  ["right_ankle", "right_heel"],
  ["right_heel", "right_foot_index"]
];
